# Generated by Django 5.2.7 on 2025-10-27 19:38

import booktracker.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(booktracker.models.BookStatus['TO_READ'], 'Chcę przeczytać'), (booktracker.models.BookStatus['READING'], 'Teraz czytam'), (booktracker.models.BookStatus['READ'], 'Przeczytane')], max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booktracker.book')),
            ],
        ),
    ]
