# Generated by Django 5.2.7 on 2025-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0002_remove_book_end_date_remove_book_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('TO_READ', 'Chcę przeczytać'), ('READING', 'Teraz czytam'), ('READ', 'Przeczytane')], default='TO_READ', max_length=10),
        ),
    ]
