# Generated by Django 5.2.7 on 2025-10-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0003_book_review_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
